
[env:spotpear_melvin]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

; --- Hardware: 8MB Flash + OPI PSRAM ---
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.psram_type = opi

; --- Upload & Serial ---
upload_protocol = esptool
upload_speed = 921600
upload_port = COM5
monitor_speed = 115200
monitor_port = COM5
monitor_filters = esp32_exception_decoder

; --- Build Flags ---
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D ARDUINO_LOOP_STACK_SIZE=16384
    -D CONFIG_ARDUHAL_LOG_DEFAULT_LEVEL=1
    -D CORE_DEBUG_LEVEL=1

; --- Libraries ---
lib_deps =
    lovyan03/LovyanGFX@^1.1.12
    bblanchon/ArduinoJson@^7.0.4
    https://github.com/schreibfaul1/ESP32-audioI2S.git
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
    https://github.com/mathieucarbou/AsyncTCP.git
