
[env:spotpear_melvin]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

; --- Память: 16MB Flash + PSRAM (qio_opi ОБЯЗАТЕЛЬНО для ps_malloc!) ---
board_build.partitions = default_16MB.csv
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi

; --- Загрузка ---
upload_protocol = esptool
upload_speed = 921600
upload_port = COM5

; --- Serial Monitor ---
monitor_speed = 115200
monitor_port = COM5
monitor_filters = esp32_exception_decoder

; --- Флаги сборки ---
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D BOARD_HAS_PSRAM
    -D ARDUINO_LOOP_STACK_SIZE=16384
    -D CONFIG_ARDUHAL_LOG_DEFAULT_LEVEL=1
    -D CORE_DEBUG_LEVEL=1

; --- Библиотеки ---
lib_deps =
    lovyan03/LovyanGFX@^1.1.12
    bblanchon/ArduinoJson@^7.0.4
    https://github.com/schreibfaul1/ESP32-audioI2S.git
    ESP32Async/ESPAsyncWebServer@^3.6.0
    ESP32Async/AsyncTCP@^3.3.2

