; PlatformIO Project Configuration File — SAY (ESP32-S3 / Arduino)
[env:esp32s3]
platform = espressif32 @ 6.6.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.partitions = partitions.csv

upload_port = COM5
monitor_port = COM5
monitor_speed = 115200

lib_deps = 
    arduino-libraries/SD @ ^1.2.4
    earlephilhower/ESP32-audioI2S @ ^2.0.7

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1