# Generated by Django 5.2.3 on 2025-07-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chips',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='chips/images/'),
        ),
    ]
