# Generated by Django 5.2.3 on 2025-09-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vote_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
