; PlatformIO Project Configuration File — SAY (ESP32-S3 / Arduino)
[env:esp32s3]
platform = espressif32 @ 6.6.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB

; Настройка для корректного определения PSRAM (OPI)
board_build.arduino.memory_type = qio_opi

lib_deps =
    esphome/ESP32-audioI2S @ ^2.3.0

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
